config/routes.rb
AdoptMeme::Application.routes.draw do
  resources :users, :only => [:index, :new, :create]
  resource :session, :only => [:new, :create, :destroy]
  root :to => "static_pages#root"
  namespace :api do
    resources :captions, :only => [:create, :index, :new, :show, :update]
    resources :images, :only => [:index]
    resources :proxy_images, :only => [:show]
  end

  get "/:captionid/new", to: "captions#new"
  get "/:captionid", to: "captions#show"

end

app/models/caption.rb
class Caption < ActiveRecord::Base
  attr_accessible :bottom_text,
                  :bottom_text_align,
                  :top_text,
                  :top_text_align,
                  :image_id,
                  :image,
                  :captioner_id

  include Storable

  validates :image_id, :presence => true

  belongs_to :image
  belongs_to :captioner, :foreign_key => :captioner_id, :class_name => "User"

  delegate :pet, :to => :image, :prefix => true

  def aws_resource_name
    "caption/#{self.aws_id}.png"
  end
end

app/controllers/api/captions_controller.rb
class Api::CaptionsController < ApplicationController
  def index
    @captions = Caption.limit(10)
    render :json => @captions, :include => :image_pet
  end

  def new
    @image = Image.find(params[:imageid])
    render :new
  end

  def create
    @caption = Caption.create(params[:caption])
    if @caption.save
      render :json => @caption, :include => :image_pet
    else
      puts @caption.errors.full_messages
      render :json => @caption.errors.full_messages, :status => :bad_request
    end
  end

  def update
    @caption = Caption.find(params[:id])
    @img_blob = decode_img_data(params[:imgData])
    @caption.create_aws_object(@img_blob)
    render :json => true # Ajax expects a JSON response.
  end

  def show
    @caption = Caption.find(params[:id])
    if !!@caption
      render :json => @caption, :include => :image_pet
    else
      render :json => ["No caption found"], :status => :bad_request
    end
  end

  require 'base64'

  private
    def decode_img_data(raw)
      body = raw[22..raw.length] # Strip out leading "data:image/png;base64,"
      Base64.decode64(body)
    end
end

app/controllers/captions_controller.rb
class CaptionsController < ApplicationController
  def show
    redirect_to "/##{params[:captionid]}"
  end

  def new
    redirect_to "/##{params[:captionid]}/new"
  end
end

app/views/captions/index.html.erb
<div class="cat-tile-container">
  <div class="cat-tile-column">
  <% @captions.shuffle.each do |caption| %>
    <a href='<%= "#{caption.image.id}/new" %>'>
      <div class="cat-tile">
        <img src="<%= caption.amazon_aws_url %>">
        <div class="cat-name"><h3><%= caption.image.pet.name %></h3></div>
      </div>
    </a>
  <% end %>
  </div>

<div class="cat-tile-column">
  <% @captions.shuffle.each do |caption| %>
    <a href='<%= "#{caption.image.id}/new" %>'>
      <div class="cat-tile">
        <img src="<%= caption.amazon_aws_url %>">
        <div class="cat-name"><h3><%= caption.image.pet.name %></h3></div>
      </div>
    </a>
  <% end %>
  </div>

  <div class="cat-tile-column">
  <% @captions.shuffle.each do |caption| %>
    <a href='<%= "#{caption.image.id}/new" %>'>
      <div class="cat-tile">
        <img src="<%= caption.amazon_aws_url %>">
        <div class="cat-name"><h3><%= caption.image.pet.name %></h3></div>
      </div>
    </a>
  <% end %>
  </div>

</div>

app/views/captions/new.html.erb
<script type="text/javascript">
  var PET_IMAGE_INFO = {
    amazonAWSUrl: "<%= @image.amazon_aws_url %>",
    imageId: <%= @image.id  %>
  }
</script>

<div class="editor-container">
  <h1> <%= @image.pet.name %> </h1>

  <form method="post" action="<%= captions_url %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>" >

    <input type="hidden" name="caption[image_id]" value="<%= @image.id%>">
    <input type="hidden" name="caption[captioner_id]" value="1">
    <input type="hidden" name="caption[top_text_align]" value="center">
    <input type="hidden" name="caption[bottom_text_align]" value="center">

<input type="text" name="caption[top_text]" placeholder="Top text" id="toptext" autocomplete="off">
  <br>
    <div class="canvas-container">
        <canvas id="catCanvas"></canvas>
    </div>

    <br><input type="text" name="caption[bottom_text]" placeholder="Bottom text" id="bottomtext" autocomplete="off">
<br>
<p>
 <div id="top-align-btns"class="btn-group">
      <a class="btn btn-default" href="#"><i class="fa fa-align-left"></i></a><a class="btn btn-default selected" href="#"><i class="fa fa-align-center"></i></a><a class="btn btn-default" href="#"><i class="fa fa-align-right"></i></a>
  </div> Ignore me for now.
</p>
  <a href="#" class="btn submit">Create meme!</a>
  <input type="submit">
  </form>

</div>

app/views/captions/show.html.erb
<img src="<%= @caption.amazon_aws_url %>">